### ISSUE TITLE
CUDA support enabled?

### ISSUE THREAD

**Issue by lukasIO** [vvvv/VL.OpenCV#1]
Just wanted to ask if the GPU support in the underlying opencvsharp library is enabled/working...?

**Comment by tebjan** [comment]
as in the stream yesterday explained by @ravazquez , it appears that you can't simply 'enable' CUDA. you need to compile OpenCV with CUDA for each specific hardware and configuration. so no, not enabled:
https://youtu.be/4hPH5CokxwQ?t=55m18s

also this might help, you could try to compile it with CUDA for your hardware yourself:
https://docs.opencv.org/3.0-beta/modules/cuda/doc/introduction.html

**Comment by lukasIO** [comment]
ah, ok, thanks for the explanation, I didn't watch the video before...
