### ISSUE TITLE
sort out transformation btw. opencv/opengl/dx

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.OpenCV#12]
see also #3 
- [x] document the problem and solution

**Comment by ravazquez** [comment]
Documentation can be found here: [https://github.com/vvvv/VL.OpenCV/wiki/Coordinate-system-conversions-between-OpenCV,-DirectX-and-vvvv](https://github.com/vvvv/VL.OpenCV/wiki/Coordinate-system-conversions-between-OpenCV,-DirectX-and-vvvv)

Issue has been resolved.

**Comment by mhusinsky** [comment]
I'd like to reopen this issue as the current solution assumes VVVV projection space, which is essentially a streched DX cube (X: -1 to 1 , Y: -1 to 1, Z: -1 to 1) - like OpenGL does it. However, this assumption is not true for the DX11 cube, which is unmodified X: -1 to 1 , Y: -1 to 1, **Z: 0 to 1**.

The projection matrix output by ApplyNearAndFar is therefore wrong when working with DX11 - the transformations (scale, translate) are simply not nescessary

![grafik](https://user-images.githubusercontent.com/3253299/57009665-4bd7b500-6bf8-11e9-9026-a2fce701a9f0.png)

It would probably make sense to have a switch here (that needs to propagate through up to the VVVV nodes) to make the extrinsics conversion configurable for EX9 or DX11 Renderer use.

**Comment by gregsn** [comment]
didn't vux apply the same idea back in the days in order to be compatible to our camera modules and perspective node set. He was asking for the exact transformation steps back then, including the -1..1 idea.

**Comment by mhusinsky** [comment]
i'm pretty sure he did not. easy to check: create a renderer with a plain quad and move it back a little into -z -> it disappears (i.e. it's not inside clip space any more)

[here](https://discourse.vvvv.org/t/draw-camera-frustum/16798/3?u=motzi) i did a more elaborate visualization once of this property once

**Comment by gregsn** [comment]
interesting. that would mean that the seen frustum is different when you connect one and the same camera to a renderer9 and a renderer11

**Comment by gregsn** [comment]
wait. it looks like he applied the same transformation to get from a vvvv projection space idea (z=-1..1) to a directx projection space (z=0..1) idea:
[Camera_ViewFrustrum_Comparison.zip](https://github.com/vvvv/VL.OpenCV/files/3153756/Camera_ViewFrustrum_Comparison.zip)
the output looks the same

**Comment by mhusinsky** [comment]
right, i was not aware that those VVVV-style transforms are undone internally. it's a little confusing if you don't know about the inner workings and assume a DX-style canonical viewing volume.

i guess this can be closed again then. sorry for the confusion.

**Comment by gregsn** [comment]
sure. on the other hand: this is just how vvvv spaces work. I guess it is valid to differ from the underlying technology and introduce own ideas and concepts. If only the documentation would be better? 
- [ ] TODO: copy some detailed information about spaces to here: https://vvvv.org/documentation/coordinate-systems. https://vvvv.org/blog/aspect-ratio-and-projection-space and tell more about z -1..1.
Anyways: the intuition 20 years ago was this: if we use particles for 2d animations we want to have them on z=0. having a projection space going from 0..1 feels like dangerous. what if we just show -1..1 in each direction and define this as our projection space?? the rest is history.
