### ISSUE TITLE
Renderer improvements

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.OpenCV#19]
- [x] add bounds input
- [x] add label input
- [x] add aspect ratio scale and make it default
- [x] add info overlay

**Comment by ravazquez** [comment]
Closed by:
310c8d51875bcbd32d673456aa68e21fc7d5428e
b8cb5d0c13a66796776e39e28853b17a27b3cf58
4c023acf83fe40092beabdf55cf602258b3b8f2b
e59f602fa1bfe8f863ad2d0476e256abe6e0eebd
