### ISSUE TITLE
.Sink error on install

### ISSUE THREAD

**Issue by preamptive** [vvvv/VL.OpenCV#28]
I cant get the example up and running. There seems to be an issue with .Sink Renderer Stack
not found stack
dependency sysytem.reflection.vl

Im new to vvvv so sorry if im doing something obvious wrong but how can i fix this?

**Comment by ravazquez** [comment]
Hi @preamptive , which version of vvvv are you trying to run the examples on? VL.OpenCV is meant to be used with alphas.

**Comment by preamptive** [comment]
Ahh thanks that will be the issue then. Running on the beta as I presumed it would be more stable? Thanks for letting me know.
