### ISSUE TITLE
ToProjectionTransform shift in Y (Principalpoint offset) inverted

### ISSUE THREAD

**Issue by tomeic** [vvvv/VL.OpenCV#3]
The problem shows up when a camera has a principal Point shifted in Y direction. (or the calibration simply thinks so)

When feeding the "Camera Matrix" from "Calibrate Camera" into "ToProjectionTransform" to get a valid projection matrix in v4 the shift in Y is going the other direction.

A quick fix is to multiply slice  9 of the v4 matrix by -1.

**Comment by joreg** [comment]
frankly the whole transformation (view/projection) situation between opencv and dx is still a bit of a mess that has to be sorted. this will help us figure things out, so thanks for pointing this out!

**Comment by tebjan** [comment]
this slide should help, get an understanding of how the basis vectors of the openCV system is represented in our system and then push everything thru the matrix: https://docs.google.com/presentation/d/14rxW-qZ0ZwDIppdc_4uGGYc_Fdm10NbYLMXOKGZ-BCg/edit#slide=id.g549de07e3_125

**Comment by tomeic** [comment]
![perspective scale](https://user-images.githubusercontent.com/13645059/38396891-ccf11a74-393a-11e8-9315-629d3f7c554e.JPG)
It seems to work if inside Perspective, the scale is below the multiply.

**Comment by ravazquez** [comment]
@tomeic we are tracking down this issue. Can you give us more information as to what camera you are using or why the principal point is flipped in the Y axis please?

**Comment by tomeic** [comment]
@ravazquez It was some random IDS camera. Apparently  the lens was "quite" offcenter and after calibration it showed a significant amount of shift in Y. (Principal point) And when overlaying a 3D scene with the same calibration parameters it didn't fit properly. The principal point was shifted but in the opposite direction. Flipping that offset and all fit well. Only Y seemed flipped.

**Comment by ravazquez** [comment]
@tomeic thanks for the information, we will test here with IDS cameras and try to replicate.

We have cleaned up the transformation pipeline used in VL.OpenCV quite a bit so if you can have a look [here](https://github.com/vvvv/VL.OpenCV/wiki/Coordinate-system-conversions-between-OpenCV,-DirectX-and-vvvv) and test again with the latest VL.OpenCV nuget, hopefully things will behave properly now.

**Comment by joreg** [comment]
closing for lack of feedback.
