### ISSUE TITLE
DrawText improvements

### ISSUE THREAD

**Issue by joreg** [vvvv/VL.OpenCV#30]
- fails with empty text input
- set default text input "vvvv"
- the default position should be visible (now out of image topleft)
- can the fontsize be in pixels?

**Comment by ravazquez** [comment]
> - the default position should be visible (now out of image topleft)

what would be a sensible default for this? are you suggesting default to be dynaimc based on image dimensions? also, how to distinguish default state form actual user input 0,0?

> - can the fontsize be in pixels?

seems like not according to this: https://docs.opencv.org/4.1.1/d6/d6e/group__imgproc__draw.html#ga5126f47f883d730f633d74f07456c576

**Comment by joreg** [comment]
i don't have a better idea than placing text at 100/100 so that it is most likely visible by default.

regarding size: ok, so be it then.

**Comment by ravazquez** [comment]
Items 1 and 2 fixed by 364420c9b0617751d03e1f6c74c1847fb80a1d13 and 8825f47c14ef5996ba85f556236243e2e04f9363
