### ISSUE TITLE
Aruco Marker: no way to enable CornerRefinement?

### ISSUE THREAD

**Issue by tomeic** [vvvv/VL.OpenCV#4]
By default the CornerRefinement is disabled. Which makes the detection a bit jittery and only outputs integer pixel values. 
From the documentation It can be enabled by:
bool doCornerRefinement
but exactly this parameter doesn't show up in VL under Aruco-->DetectorParamters, all the other parameters are there.

**Comment by tomeic** [comment]
I also think that the image doesn't need to be undistored before going to the detector. Because EstimatePose also takes the "Distortion Coefficients". Basically corner detection on the distorted image and pose estimation with distortion compensation. Make sense Performance wise and also looks better. (with my current setup)
I guess it should be like that:
![arucopatch](https://user-images.githubusercontent.com/13645059/38176895-7386e6a8-35f7-11e8-91a1-8284605428eb.JPG)

**Comment by joreg** [comment]
indeed "SetDoCornerRefinement" or "SetCornerRefinementMethod" (not sure which one we should expect really) seem to be missing from the underlying opencvsharp wrapper. so this should be reported over at https://github.com/shimat/opencvsharp/issues

regarding order of undistort and markerdetection, yep that sounds plausible, will check that.

**Comment by joreg** [comment]
regarding order of undistort and markerdetection: adapted the demo accordingly.

**Comment by ravazquez** [comment]
@tomeic ,

After looking a bit into this, it seems as though the property is commented out in OpenCVSharp as you can see here: [https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Modules/aruco/DetectorParameters.cs#L251](url)

I continued looking into it and noticed that starting with version 3.3.0 in opencv "doCornerRefinement" is missing, suggesting it was deprecated or dropped.  This is most likely why OpenCVSharp commented it out.

Use this link and toggle between different versions with the dropdown at the top: [https://docs.opencv.org/3.3.0/d1/dcd/structcv_1_1aruco_1_1DetectorParameters.html](url)

Hope that helps clarify things a bit.

**Comment by clmens** [comment]
using this nuget package with VL.OpenCV: 

https://www.nuget.org/packages/OpenCvSharp3-AnyCPU/3.4.1.20181108

enables to setCornerRefinementMethods and thereby enables corner accuracies below integer accuarcy.
(i have not tested it currently but it shows the relevant nodes that are needed).

**Comment by ravazquez** [comment]
Fixed by 63d4aae3fdc418e926d6165dafda145995d0cc7f
