### ISSUE TITLE
Xenko-to-Stride update required for the pack

### ISSUE THREAD

**Issue by YanYas** [vvvv/VL.OpenCV#44]
Gamma 2020.2.225 and above are currently breaking VL.OpenCV 0.2.133-alpha. I think this may be related to this error, or is this seperate?:
![image](https://user-images.githubusercontent.com/9497052/92457522-9d1c8f00-f1c4-11ea-96bc-04164ff7f1dd.png)

**Comment by ravazquez** [comment]
This was fixed a while ago for the release of 2020.2.2
