### ISSUE TITLE
ObjectDetector (CustomFile) always sees empty files

### ISSUE THREAD

**Issue by sebescudie** [vvvv/VL.OpenCV#5]
On b36,  VL.OpenCV 0.2.10-alpha. 

When setting the `Classifier File` pin of `ObjectDetector (CustomFile)`, the node turns pink and complains the file is empty (tooltip says `!empty()`). The file is indeed not empty, vvvv can display its content with `Reader (String)`.

Opening the ObjectDetector, I noticed the `ptr` property of the CascadeClassifier keeps changing at every frame, since the Condition of the If region is always true, is that intended behavior ?

**EDIT :** The tooltip of the Path IOBox going in ObjectDetector says the size property is null :/

![capture_detectobject_vl](https://user-images.githubusercontent.com/8690430/38567788-56659fdc-3ce7-11e8-998e-b5841ca5aa67.PNG)

**Comment by ravazquez** [comment]
Hi, @sebescudie ,

The changing ptr was a bug and was corrected in version 0.2.11-alpha (still indexing on nuget.org at the time of this posting).

As for your file not working, I tested using one of the provided sample files located in \VL.OpenCV\content\haarcascades\  with version 0.2.11-alpha and am not getting any pink nodes.

Could you please test and report?  If possible also please provide your haarcascade file for reference.

Thanks!

**Comment by sebescudie** [comment]
Hi @ravazquez,

Tested again with the same XML file on b36 with VL.OpenCV 0.2.8-alpha, all is running fine. This is the file I'm using for reference : [finger.xml](https://raw.githubusercontent.com/PrafulBhosale/Finger-Detection-Application/master/DetectFingerProject/cascade.xml).

Thanks for checking this out.
