### ISSUE TITLE
Renderer break under certain coniditons with VideoPlayer

### ISSUE THREAD

**Issue by jmaldon1** [vvvv/VL.OpenCV#54]
Firstly I noticed this only seems to happen with square videos (i.e. 720x720 or 1080x1080 videos).

![image](https://user-images.githubusercontent.com/25569545/140396457-334bec1a-456f-400d-964a-eaddf3af9601.png)

versions:
  vvvv = 2021.3.3 also tried 2021.4.0-0458
  vl.opencv = 2.1.0
  opencvsharp = 4.4.5.3.20210725
  opencvsharp.runtime.win = 4.4.5.3.20210725

Error:
If you create a Renderer node and a VideoPlayer node (with a square video file loaded) and then connect the two of them you get an error from the Renderer node.

2 different work arounds:
1. If you create a VideoPlayer node (with a square video file loaded) drag the output link and then double click and create a Renderer node directly attached to the link, it works.

2. When you get the Renderer error, switch the video file to something that isnt square and then back to the square video.

**Comment by joreg** [comment]
thanks for that. continues in #55
