### ISSUE TITLE
EstimatePose crashes VVVV hard when no intrinsics are present

### ISSUE THREAD

**Issue by mhusinsky** [vvvv/VL.OpenCV#56]
try this to reproduce:
* open e.g. the "Calculate a Camera Position using Aruco" help patch.
* disconnect the Intrinsics link from the "EstimatePose" pin
* show the camera an aruco marker
as  soon as the marker is detected, VVVV crashes hard. that's not nice. a check for intrinsics present would probably suffice...

VVVV@ 21.4.7
VL.OpenCV@ 2.1.0

![grafik](https://user-images.githubusercontent.com/3253299/156384390-4c3fe662-7e29-42c8-9085-12072619fc2e.png)

**Comment by ravazquez** [comment]
Apparently this is still causing issues: https://discourse.vvvv.org/t/crash-on-saving-to-other-locations-opening-patch-opencv-poseestimate-aruco-markers-detection/20371/9

**Comment by ravazquez** [comment]
Fixed by 2c59e183e0c15de3454b1bfce00c310971644965 and aa299c7f05af8dfc1ddfabea1d7083159497f30b
