### ISSUE TITLE
Some dependencies should be updated / removed

### ISSUE THREAD

**Issue by azeno** [vvvv/VL.OpenCV#58]
There's a nuget referenced in the document which is not expressed as a dependency in the nuspec - either remove it or add it as a dependency.
![image](https://user-images.githubusercontent.com/573618/169690548-fbd8a1c2-aa47-4849-a6a7-3761da686897.png)

Stride  and VL.Video.MediaFoundation are referencing a newer version of SharpDX.MediaFoundation. Usually that's not an issue but in case of VL.OpenCV I saw a `MethodNotFoundException` when opening the "Detect faces" help patch which could point to a ABI incompatibility issue. So it's worth a shot to simply update that one to the same version and recompile.
![image](https://user-images.githubusercontent.com/573618/169690562-68fd02c5-931f-4794-83fa-9ca3c7168ac4.png)

```
Method not found: 'SharpDX.MediaFoundation.Activate[] SharpDX.MediaFoundation.MediaFactory.EnumDeviceSources(SharpDX.MediaFoundation.MediaAttributes)'.
```

**Comment by ravazquez** [comment]
This is now fixed as of VL.OpenCV 2.5.0
